Practica 2 : Mediante el fichero de excel "DAtos telefonia-..." consolidar los meses de enero a junio en un solo dataframe, crear una columna que me de el "importe factura neto" que sera igual al importe fra despues de aplicar un descuento del 8,39% solo a los clientes que necieron los dias 1, 5 o 10 de cualquier mes. Para el resto el Importe Fraa neto = Importe FRA 
Queremos tener en una lista las diferentes localidades del campo localidad y despues queremos ver la suma de importe FRa neto de los clientes del servicio ADSL + Movil (dos servicios)

In [1]:
# Importar y consolidar datos Limpiand nulos si los hay

import pandas as pd
ruta_fichero = "/Users/rogerdefez/Documents/Cursos i Llibres/Curso Barcelona Activa/2026-04-29_Python3_Ciencia-de-datos-Python-Institute-PCAD-31-Ed2/Datos_originales/Datos Telefonia Separados Meses Comerciales URL.xlsx"

fras_enero = pd.read_excel(ruta_fichero,sheet_name="Facturación Enero 2020", header=2)

fras_febrero = pd.read_excel(ruta_fichero,sheet_name="Facturación Febrero 2020")

fras_marzo = pd.read_excel(ruta_fichero,sheet_name="Facturación Marzo 2020",header=1)

fras_abril = pd.read_excel(ruta_fichero,sheet_name="Facturación Abril 2020",header=1)

fras_mayo = pd.read_excel(ruta_fichero,sheet_name="Facturación Mayo 2020",header=1)

fras_junio = pd.read_excel(ruta_fichero,sheet_name="Facturación Junio 2020",header=2)

fras_semestre = pd.concat([fras_enero, fras_febrero, fras_marzo, fras_abril, fras_mayo, fras_junio], ignore_index=True)
fras_semestre = fras_semestre.dropna(how='all')

fras_semestre['Dia Nac'] = fras_semestre['Fecha Nacimiento'].dt.day.astype('Int64') # con Astype modifico el tipo de dato para que no me salgan decimalesConvierto 

fras_clientes_1 = fras_semestre[fras_semestre['Dia Nac'].isin([1,5,10])]
fras_clientes_1


fras_semestre_AN1510 =  fras_semestre[(fras_semestre['Fecha Nacimiento'].dt.day == 1) |
                        (fras_semestre['Fecha Nacimiento'].dt.day == 5) |
                        (fras_semestre['Fecha Nacimiento'].dt.day == 10)]

fras_semestre_AN1510['importe factura neto'] = round(fras_semestre_AN1510['Importe factura']*(1-0.0839),2)


fras_semestre_ANNO1510 =  fras_semestre[(fras_semestre['Fecha Nacimiento'].dt.day != 1) | 
                        (fras_semestre['Fecha Nacimiento'].dt.day != 5) | 
                        (fras_semestre['Fecha Nacimiento'].dt.day != 10)]

fras_semestre_ANNO1510['importe factura neto'] = 0
fras_semestre = pd.concat([fras_semestre_AN1510, fras_semestre_ANNO1510])

localidad_fras_semestre = fras_semestre['Localidad'].unique()
print(localidad_fras_semestre)

filtro_ADSL_Movil = (fras_semestre['Servicios'] == 'ADSL') | (fras_semestre['Servicios'] == 'Móvil')
suma_importe_FRA_neto_filtradas = fras_semestre[filtro_ADSL_Movil]['importe factura neto'].sum()

print(f"La suma de los importes factura neto de los clientes de servicios ADSL y Móvil es: {suma_importe_FRA_neto_filtradas}")

<StringArray>
['Castilla La Mancha',            'Galicia',           'Asturias',
          'Santander',             'Madrid',           'Baleares',
          'Andalucía',          'Barcelona',             'Bilbao',
           'Valencia',    'Castilla y León']
Length: 11, dtype: str
La suma de los importes factura neto de los clientes de servicios ADSL y Móvil es: 34987.68

In [2]:
# Importar y consolidar datos Limpiand nulos si los hay

import pandas as pd
ruta_fichero = "/Users/rogerdefez/Documents/Cursos i Llibres/Curso Barcelona Activa/2026-04-29_Python3_Ciencia-de-datos-Python-Institute-PCAD-31-Ed2/Datos_originales/Datos Telefonia Separados Meses Comerciales URL.xlsx"

fras_enero = pd.read_excel(ruta_fichero,sheet_name="Facturación Enero 2020", header=2)

fras_febrero = pd.read_excel(ruta_fichero,sheet_name="Facturación Febrero 2020")

fras_marzo = pd.read_excel(ruta_fichero,sheet_name="Facturación Marzo 2020",header=1)

fras_abril = pd.read_excel(ruta_fichero,sheet_name="Facturación Abril 2020",header=1)

fras_mayo = pd.read_excel(ruta_fichero,sheet_name="Facturación Mayo 2020",header=1)

fras_junio = pd.read_excel(ruta_fichero,sheet_name="Facturación Junio 2020",header=2)

fras_semestre = pd.concat([fras_enero, fras_febrero, fras_marzo, fras_abril, fras_mayo, fras_junio], ignore_index=True)
fras_semestre = fras_semestre.dropna(how='all')

fras_semestre['Dia Nac'] = fras_semestre['Fecha Nacimiento'].dt.day.astype('Int64') # con Astype modifico el tipo de dato para que no me salgan decimalesConvierto 

#Ponemos en un DF los clientes que nacieron ese dia
fras_clientes_1 = fras_semestre[fras_semestre['Dia Nac'].isin([1,5,10])]

#Comprobar si los numeros unicos coinciden 
fras_clientes_1['Dia Nac'].unique()

#Ponemos en un df los clientes que no nacieron estos dias
# La virvulilla hace lo contrario de lo que viene a continuacion
fras_clientes_2 = fras_semestre[~fras_semestre['Dia Nac'].isin([1,5,10])]
fras_clientes_2['Dia Nac'].unique()

fras_clientes_1['importe factura neto'] = round(fras_clientes_1['Importe factura']*(1-0.0839),2)
fras_clientes_2['importe factura neto'] = fras_clientes_2['Importe factura']

fras_semestre = pd.concat([fras_clientes_1, fras_clientes_2], ignore_index=True)

localidad_fras_semestre = fras_semestre['Localidad'].unique()
print(localidad_fras_semestre)

filtro_servicio = (fras_semestre['Servicios'] == 'ADSL') | (fras_semestre['Servicios'] == 'Móvil')

filtro_importe_neto = (fras_semestre['importe factura neto']>30)

fras_semestre = fras_semestre[filtro_servicio]

suma_importe = round(fras_semestre['importe factura neto'].sum())

print(f"La suma de los importes factura neto de los clientes de servicios ADSL y Móvil es: {suma_importe}")

<StringArray>
['Castilla La Mancha',            'Galicia',           'Asturias',
          'Santander',             'Madrid',           'Baleares',
          'Andalucía',          'Barcelona',             'Bilbao',
           'Valencia',    'Castilla y León']
Length: 11, dtype: str
La suma de los importes factura neto de los clientes de servicios ADSL y Móvil es: 341773

In [3]:
# El resultado de una diferencia entre 2 fechas , tambien es una instancia de la clase datetime

from datetime import date as fecha

#referencia al dia de hoy con today()
hoy = fecha.today()

# Ajustar una fecha especifica
fecha_pedido = fecha(2026,10,14)

#Puedo comparar 2 instancias de la clase date, pero no un date con un datetime
if hoy>fecha_pedido:
    print ("la fecjha hoy", hoy, "es mayor que ",fecha_pedido)
else:
    print ("la fecjha hoy", fecha_pedido, "es mayor que ",hoy)

la fecjha hoy 2026-10-14 es mayor que  2026-04-30

In [4]:
# Como calcular el tiempo transcurrido entre 2 fechas
#mediante una resta (es la fecha + nueva meos la fecha + antigua)

dias = fecha_pedido - hoy

# El resultado lo puedo averiguar porque dias es una instacia de date, por lo que tengo sus atributos 

print("los dias transcurridos son", dias.days)

los dias transcurridos son 167

In [5]:
# Como ajustar la configuracion regional ---> con locale

import locale

#Ajustar la configuracion regional

locale.setlocale(locale.LC_TIME, "es_ES")

'es_ES'

In [6]:
#Como dar formato a las fechas , clases (date + datetime) con strftime. (string format time)

print ("el dia de hoy es",hoy.strftime('%d'))

print ("el dia de hoy en letras es",hoy.strftime('%A'))

# dia de la semana
print ("el dia de hoy es",hoy.strftime('%w'))

# el mes de hoy es
print ("el mes de hoy es",hoy.strftime('%m'))

print ("el mes de hoy en letra es",hoy.strftime('%B'))

print ("la semana del año es",hoy.strftime('%W'))

print ("el año de hoy es",hoy.strftime('%Y'))

#Como personalizar una fecha año-mes-dia   2026-04-30

print(hoy.strftime('%d/%m/%Y'))

# aplicado a una columna datetime de pandas

# df['Campo'].dt.strftime('%d/%m/%Y')
# sino, primero convertir con pd.to_datetime(df['Fecha Fra'])

el dia de hoy es 30
el dia de hoy en letras es jueves
el dia de hoy es 4
el mes de hoy es 04
el mes de hoy en letra es abril
la semana del año es 17
el año de hoy es 2026
30/04/2026

In [7]:
# La clase timedelta que viene con la libreria datetime, permite incrementar o decremetar tiempo

from datetime import datetime, timedelta

hoy = datetime.now()

#incrementar 10 dias a la fecjha de hoy

hoy2 = hoy + timedelta(days=10, hours=3)
print (hoy2)

2026-05-10 20:32:41.444939

In [8]:
# Es calcular la edat actual en funcion de una fecha de nacimiento
import pandas as pd

alumnos = {'Nombre' : ['Maria', 'Luis', 'Alvaro', 'Sonia'],
           'Fecha Nac': ['1994-05-14','1985-06-20','2001-03-07','1978-11-18']}
clase = pd.DataFrame(data=alumnos)

# LA columna no es fecha
clase['Fecha Nac'] = pd.to_datetime(clase['Fecha Nac'])

# Ver año mes y dia
clase['Fecha Nac'].dt.year
clase['Fecha Nac'].dt.month
clase['Fecha Nac'].dt.day
clase['Fecha Nac'].dt.dayofweek #dia semana del 1 al 7
clase['Fecha Nac'].dt.day_name() #Dia semana en letras
clase['Fecha Nac'].dt.month_name() 

#Guardar en una columna el numero de dias entre la fecha de nacimiento y hoy
# es un metodo de pandas que equivale a timedelta, se llama timestamp

clase['Dias'] = (pd.Timestamp('today') - clase['Fecha Nac']).dt.days

#calcular la edasd aproximada
clase['Edad'] = clase['Dias'] // 365

#calcular su decada teniendo en cuenta que va de 
# 10-19 = Decada 10
# 20-29 = Decada 20
# 30-39 = Decada 30
clase['Decada'] = (clase['Edad'].astype('str').str[0] + '0').astype('Int64')
clase

   Nombre  Fecha Nac   Dias  Edad  Decada
0   Maria 1994-05-14  11674    31      30
1    Luis 1985-06-20  14924    40      40
2  Alvaro 2001-03-07   9185    25      20
3   Sonia 1978-11-18  17330    47      40

Practica 3 : Partiendo del Dataframe 'fras_semestres', averiguar la suma de importe neto de los clientes que nacieron un mes de mayo o septiembre.
Calcular la edad del cliente y si es mayor de 40 años poner en la columna neva 'VIP' = SI, si no VIP = NO
Crear una columna que nos diga 15  dias antes en que dia y mes debemos enviar al cliente una felicitacion de cumpleaños.

In [9]:
import pandas as pd
import locale
locale.setlocale(locale.LC_TIME, "es_ES")
fras_semestre['Mes Nac'] = fras_semestre['Fecha Nacimiento'].dt.month_name() 

filtro_nacimiento = (fras_semestre['Mes Nac'] == 'May') | (fras_semestre['Mes Nac'] == 'September')

fras_semestre_filtradas = fras_semestre[filtro_nacimiento]
resultado = fras_semestre_filtradas['importe factura neto'].sum()
print(resultado)

53406.68

In [10]:

#Calcualr la edad del cliente

fras_semestre['Dias'] = (pd.Timestamp('today') - fras_semestre['Fecha Nacimiento']).dt.days
fras_semestre['Edad'] = fras_semestre['Dias'] // 365

# Voy a crer una funcion para aplicarla al nuevo campo
def clasificar_vip(edad):
    if edad > 40:
        return "SI VIP"
    else:
        return "NO VIP"

# crear campo VIP nuevo
fras_semestre['VIP'] = fras_semestre['Edad'].apply(clasificar_vip)
fras_semestre
    


fras_semestre

,Nombre,Servicios,Genero,Fecha Nacimiento,Localidad,Fecha factura,Importe factura,Satisfacción,IdComercial,Dia Nac,importe factura neto,Mes Nac,Dias,Edad,VIP
1,Cliente 1011,ADSL,Femenino,1974-12-01,Galicia,2020-01-01,65.0,6.0,3.0,1,59.55,December,18778,51,SI VIP
2,Cliente 1012,ADSL,Femenino,1983-04-01,Asturias,2020-01-01,54.0,7.0,3.0,1,49.47,April,15735,43,SI VIP
5,Cliente 1031,Móvil,Femenino,1980-02-10,Madrid,2020-01-01,22.0,6.0,4.0,10,20.15,February,16881,46,SI VIP
6,Cliente 104,Móvil,Masculino,1953-11-01,Baleares,2020-01-01,43.0,0.0,5.0,1,39.39,November,26478,72,SI VIP
9,Cliente 1055,Móvil,Masculino,1994-07-10,Galicia,2020-01-01,54.0,6.0,9.0,10,49.47,July,11617,31,NO VIP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12141,Cliente 994,ADSL,Masculino,1985-03-19,Barcelona,2020-06-01,56.0,5.0,9.0,19,56.00,March,15017,41,SI VIP
12143,Cliente 996,Móvil,Femenino,1963-09-16,Barcelona,2020-06-01,44.0,2.0,3.0,16,44.00,September,22872,62,SI VIP
12144,Cliente 997,Móvil,Femenino,1976-08-27,Baleares,2020-06-01,48.0,5.0,1.0,27,48.00,August,18143,49,SI VIP
12145,Cliente 998,Móvil,Masculino,1954-10-17,Barcelona,2020-06-01,50.0,0.0,3.0,17,50.00,October,26128,71,SI VIP
12146,Cliente 999,Móvil,Femenino,1954-01-23,Valencia,2020-06-01,37.0,5.0,1.0,23,37.00,January,26395,72,SI VIP

In [12]:
#Crear una columna que nos diga 15  dias antes en que dia y mes 
# debemos enviar al cliente una felicitacion de cumpleaños.

fras_semestre['Fecha Aviso'] = fras_semestre['Fecha Nacimiento'] - timedelta(days=15)
fras_semestre['Fecha Aviso'] = fras_semestre['Fecha Aviso'].dt.strftime('%d/%m')
fras_semestre

,Nombre,Servicios,Genero,Fecha Nacimiento,Localidad,Fecha factura,Importe factura,Satisfacción,IdComercial,Dia Nac,importe factura neto,Mes Nac,Dias,Edad,VIP,Fecha Aviso
1,Cliente 1011,ADSL,Femenino,1974-12-01,Galicia,2020-01-01,65.0,6.0,3.0,1,59.55,December,18778,51,SI VIP,16/11
2,Cliente 1012,ADSL,Femenino,1983-04-01,Asturias,2020-01-01,54.0,7.0,3.0,1,49.47,April,15735,43,SI VIP,17/03
5,Cliente 1031,Móvil,Femenino,1980-02-10,Madrid,2020-01-01,22.0,6.0,4.0,10,20.15,February,16881,46,SI VIP,26/01
6,Cliente 104,Móvil,Masculino,1953-11-01,Baleares,2020-01-01,43.0,0.0,5.0,1,39.39,November,26478,72,SI VIP,17/10
9,Cliente 1055,Móvil,Masculino,1994-07-10,Galicia,2020-01-01,54.0,6.0,9.0,10,49.47,July,11617,31,NO VIP,25/06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12141,Cliente 994,ADSL,Masculino,1985-03-19,Barcelona,2020-06-01,56.0,5.0,9.0,19,56.00,March,15017,41,SI VIP,04/03
12143,Cliente 996,Móvil,Femenino,1963-09-16,Barcelona,2020-06-01,44.0,2.0,3.0,16,44.00,September,22872,62,SI VIP,01/09
12144,Cliente 997,Móvil,Femenino,1976-08-27,Baleares,2020-06-01,48.0,5.0,1.0,27,48.00,August,18143,49,SI VIP,12/08
12145,Cliente 998,Móvil,Masculino,1954-10-17,Barcelona,2020-06-01,50.0,0.0,3.0,17,50.00,October,26128,71,SI VIP,02/10
12146,Cliente 999,Móvil,Femenino,1954-01-23,Valencia,2020-06-01,37.0,5.0,1.0,23,37.00,January,26395,72,SI VIP,08/01